# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('data', models.DateField()),
                ('grupa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'TAs',
                'verbose_name': 'TA',
            },
        ),
        migrations.RemoveField(
            model_name='etykieta',
            name='data',
        ),
        migrations.RemoveField(
            model_name='etykieta',
            name='grupa',
        ),
        migrations.AlterField(
            model_name='etykieta',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasma.TA'),
        ),
    ]
